### ISSUE TITLE
Connecting to Mysql ?

### ISSUE THREAD

**Issue by avremy** [AMeng/vault-web#6]
Hi
Is it possible to connect the gui to a mysql database and if so how ?
as of now when i try to click on anything , i get the following error
![error](https://cloud.githubusercontent.com/assets/22290672/18626665/1a1a7b62-7e5f-11e6-985b-adca150019c1.PNG)

the vault server is running and i can access and edit everything from the cli
maybe im missing something in the configuration

**Comment by AMeng** [comment]
There is not currently any support for MySQL. It looks like your token field is empty, you need to get a token from vault and paste it into that field.
